### ISSUE TITLE
Account shouldn't be created with empty username/password

### ISSUE THREAD

**Issue by ManitKSoni** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#1]
## Expected Behavior
Give some sort of warning that an account can't be created without filling both the username and pin field.

## Actual Behavior
Account is created

## Steps to Reproduce the Problem

  1. Head to login screen (with no account in the db)
  2. Don't fill out the username/pin fields and click "Sign-Up"

**Comment by Sasha45** [comment]
When creating an account, the user is able to use just 1 character for the PIN. This can lead to security issues

The ideal solution would be to add a length requirement and to show these instructions on the login page

Also show these instructions include: Capital letter, number and special character

close #5
