### ISSUE TITLE
Login Page UI Improvements

### ISSUE THREAD

**Issue by k9kathyli** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#10]
**Is your feature request related to a problem? Please describe.**
It's not possible to reset your PIN in case it is forgotten. 
Additionally, there is a pop-up when we log in successfully that just says "login". 

**Describe the solution you'd like**
Add a reset PIN functionality. 
Remove the pop-up altogether.

**Describe alternatives you've considered**
Alternatively, reword the popup so it is clear the login operation was successful.
**Additional context**

<img width="996" alt="Screen Shot 2022-04-27 at 6 20 28 PM" src="https://user-images.githubusercontent.com/50219351/165657308-933868f8-1308-47a8-ab1c-c7d6c687c549.png">

**Comment by Dsuzuki126** [comment]
A few things:
- I recommend you guys write jest tests as manually testing is difficult and I dont think you wrote any (but if you did please show me where)
- The password reset doesnt have any effect unless I copy and paste the url for the login page into another tab. Refreshing the page and clearing the cache doesn't work.
- when I click the "confirm" button there is still a prompt that says incorrect password
- the indexDB information doesnt reflect the change in real time hence having to go to another tab
- small thing, in LoginJS.js on line 98 there is a 'g' missing in the console.log that may cause issues
- the way you have implemented the password reset also makes it possible for a user to reset their password PIN to an empty string
- Another thing I discovered is that if I copy paste the url to another tab then go to a previous tab that I reset the password with and hard refresh the page then I can use the new PIN but the indexDB information is still wrong on the previous tab
