### ISSUE TITLE
find lost password via security question

### ISSUE THREAD

**Issue by WeMWish** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#12]
**Is your feature request related to a problem? Please describe.**
currently we do not limit the username/password, and customer might forget about their password and want to get it back, if they can't they won't be able to use the account, and we will have to keep those data forever, waiting our storage

**Describe the solution you'd like**
develop a security question system that allow user to get their password back by answering the questions correctly

**Describe alternatives you've considered**
develop a send-message-to-phone system that allow user to get password back by entering correct sent message

**Comment by Dsuzuki126** [comment]
maybe even have a way to remember username or use username/email to retrieve password?

**Comment by Sasha45** [comment]
go to #10
