### ISSUE TITLE
Changing Text CSS so that it is more readable

### ISSUE THREAD

**Issue by Dsuzuki126** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#14]
**Is your feature request related to a problem? Please describe.**
not a definite problem but we can change the design of some of the pages like the font size, color, and contrast so that some of the words are easier to read.  This would involve changing the css styles of the text

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered : 

**Additional context**

**Comment by Sasha45** [comment]
cf #19
