### ISSUE TITLE
Daily Overview Changes

### ISSUE THREAD

**Issue by Dsuzuki126** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#17]
**Is your feature request related to a problem? Please describe.**
Some UI/design changes we can make for the daily overview page.  

**Describe the solution you'd like**
For adding photos  to the photo album we can have a button that more clearly states "add photo" rather than just having a vague plus sign. 
**(For the notes we can also have a button that says "add note" that allows users to add separate notes so they don't have to write in a single text box and figure out how to separate notes)** -> refer to comments below

**Describe alternatives you've considered**

**Additional context**

**Comment by ManitKSoni** [comment]
- added "Add Photo" button
- made button look clickable
- removed bug where photo was cleared without a new photo being saved

**Comment by ManitKSoni** [comment]
Decided that "Add Note" functionality was inferior to what already exists. It would require either pressing an arrow to move from one note to another OR a longer page based on the number of notes, neither of which would be wanted by the user.
