### ISSUE TITLE
Correct passwords are printed out in the console if incorrect password is put in

### ISSUE THREAD

**Issue by AlejandroM2000** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#18]
**Is your feature request related to a problem? Please describe.**
If someone else is using the web browser on my laptop, they can get my correct password because the correct PIN is printed in JS console on the web browser

**Describe the solution you'd like**
To just not display the password in the console, as although this is useful to the user, this can cause security issues

This is in the handleLogin() function

**Comment by Sasha45** [comment]
#18 relates to this

**Comment by Sasha45** [comment]
rolled into #2 and #20
