### ISSUE TITLE
Fix back buttons

### ISSUE THREAD

**Issue by Hunter27E** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#27]
Some back buttons are not intuitive.

For example, after clicking a date from the calendar on the first landing page to go to a "Today" page, the "back button" takes you to the Month view of the current month. This is not intuitive because the previous page the user was on was not the Month view.

**Comment by Dsuzuki126** [comment]
this might be a bit harder if this is in the realm of routing but hopefully it is as simple as redirecting to the right page

**Comment by Hunter27E** [comment]
Yeah I get you, I'll look into it and update the issue if necessary.
