### ISSUE TITLE
Calendar should up to date, the previous time display read-only mode

### ISSUE THREAD

**Issue by PatriciaWuu** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#29]
**Is your feature request related to a problem? Please describe.**
Only future calendar is text-able(include To-Do, Monthly goals, yearly goals) and add pictures

**Describe the solution you'd like**
Keep track the current date and only enable future calendar text-able.

**Describe alternatives you've considered**
Hide previous years input form

**Comment by k9kathyli** [comment]
Closed because we want the user to be able to edit previous entries.
