### ISSUE TITLE
Improve mobile rendering

### ISSUE THREAD

**Issue by Sasha45** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#4]
The lack of a <meta name="viewport"> tag in the header decreases mobile-friendliness and introduces a delay.
Adding this can help us optimize the webapp for mobile use.
See https://web.dev/viewport/?utm_source=lighthouse&utm_medium=devtools for more details.

**Comment by Dsuzuki126** [comment]
On top of adding the tag header we may want to actually view how it looks on a mobile device.  We may have to design custom css style pages for different screen sizes
