### ISSUE TITLE
Insecure Login

### ISSUE THREAD

**Issue by AlejandroM2000** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#5]
## Expected Functionality
PIN length at least 4 characters that are only numbers.

## Current Functionality
No such restrictions for the PIN.

**Comment by PatriciaWuu** [comment]
Also show these instructions include: Capital letter, number and special character

**Comment by Sasha45** [comment]
merged into #1

**Comment by Sasha45** [comment]
#9 goes here
