### ISSUE TITLE
create a regex to manage the allowed characters for password/uesrname

### ISSUE THREAD

**Issue by WeMWish** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#9]
**Is your feature request related to a problem? Please describe.**
now we can type any characters / passwords into the username/password field. Having a limited alphabet is generally a good practice against malicious attack on websites.

**Describe the solution you'd like**
build a regular expression of our own and embed it in the code

**Describe alternatives you've considered**
store the allowed characters locally

**Comment by Sasha45** [comment]
merged into #5
